apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
#    this matters as an administrator as you want to control how much capacity a pod can use
  volumeMode: Block
#  this is the storage type you can have filesystem type and block storage type
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
#    can be claimed by multiple nodes
#    - ReadWriteMany
#    - ReadOnlyMany
  hostPath:
    path: /data
    type: DirectoryOrCreate